export const cloudinaryName = "mounssif-void";
export const sliderData = [
  {
    title: "#Clapclaptour21",
    content: "La campagne d'employee advocacy du groupe ELSAN",
    video: "agency africa/videos/vs8num7bxucphbcx49oo",
    image: "agency africa/thumbnails/e04hdode5nn2po8dxijq",
    id: "clapclaptour21",
  },
  {
    title: "AXA MAROC",
    content: "Campagne publicitaire pour le numéro court du service client",
    video: "agency africa/videos/ib99sx4zcritadaxiuv9",
    image: "agency africa/thumbnails/gek7asstijprmact9cn2",
    id: "axa-maroc",
  },
  {
    title: "Biogaran",
    content:
      "Film publicitaire pour la Coupe d'Afrique des Nations de Football 2024",
    video: "agency africa/videos/yungwblvs13kb21ghgoj",
    image: "agency africa/thumbnails/dapbaqvhzkypwouwrgwv",
    id: "biogaran",
  },
  {
    title: "ELSAN 20 ans",
    content:
      "Film institutionnel pour célébrer l'anniversaire du 1er opérateur de santé en France",
    video: "agency africa/videos/spg7kab9ui5zgpdyo9t6",
    image: "agency africa/thumbnails/k3hizmdlu9akhkf8ka6h",
    id: "elsan-20-ans",
  },
  {
    title: "Pernod ricard",
    content: "Le premier rapport annuel 100% vidéo",
    video: "agency africa/videos/ntlymlohqd2yqaqqqere",
    image: "agency africa/thumbnails/cdju2hdwlsdlp1hp7fb9",
    id: "pernod-ricard",
  },
  {
    title: "Africa bright",
    content:
      "Film institutionnel d'une banque d'affaire panafricaine indépendante",
    video: "agency africa/videos/qr2eeaglre9ntu0iuuwm",
    image: "agency africa/thumbnails/vt6gcbusw59y9krohg4p",
    id: "africa-bright",
  },
  {
    title: "#Clapclaptour21",
    content: "La campagne d'employee advocacy du groupe ELSAN",
    video: "agency africa/videos/letafrln2nldfv7ucj7p",
    image: "agency africa/thumbnails/srsbbelf8z5ccnzpj1yf",
    id: "clapclaptour21",
  },
  {
    title: "AXA MAROC",
    content: "Campagne publicitaire pour le numéro court du service client",
    video: "agency africa/videos/nzizzv2nl4uiqgd7pkcx",
    image: "agency africa/thumbnails/mvn3xvah8bsexcp9kf7l",
    id: "axa-maroc",
  },
];

/* [
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/bwkk2qoosstpkuwyhibt",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/bfqyuhrr6ho6wnyozfs5",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/npccpaeevqmdocceznao",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/qyfygifjxzqqesncqntb",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/kkyagwwj4xdsnz4niw7a",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/cjb6jpio9voeesggagfw",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/gupiciwqhtwafgmbyags",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/dy8hgjpylisgxyvtarxw",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/sl042wau6vwijma5snuf",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/ofxugjxma009eodw4rw1",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/yuh04wtwml5mcscfa5j7",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/numur2u4tvcxwopcivb1",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/mhwbabslhpodepjfjeap",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/pd9vvtpuinw0wqp2jbx8",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/re47mujvh6xhixbezibp",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/bymj7liqw7p8qe8of3li",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/wkutncypmvxfbfoywo02",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/ncudmxvrjqpmpbahdutx",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/siv41l4humpxcs3r33kh",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/brkxzofo3ikamzw5nfcr",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/c3ikvsuneelmykekevvc",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/e5e8vry8djg8wdeoe3vv",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/ljmhebdhihpjmjawfir6",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/iufbcc2elfkbgq7pijar",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/tlrqocydpevsqf6iblqn",
    id: "",
  },
  {
    title: "",
    content: "",
    image: "",
    video: "agency_africa/videos/pumi2bgyffj69aec2o4l",
    id: "",
  },
];
 */